#!/bin/bash

printf "\n\n\nDo you wish to distill openmaths-app?\n\n"

select yn in "Yes" "No"; do
	case $yn in
		Yes )
			gulp concatVendor compile-tsc compile-tsc-tests && gulp test

			rm -r dist
			mkdir dist && mkdir dist/app && mkdir dist/app/dist

			cp app/dist/app.js dist/app/dist && cp app/dist/vendor.js dist/app/dist
			cp index.html dist/index.html

			cp -r app/_shared dist/app
			cp -r app/components dist/app
			cp -r app/utils dist/app

			tar -v -cf openmaths-app.tar app/* .gitignore bower.json gulpfile.js index.html package.json
            mv openmaths-app.tar dist/openmaths-app.tar

			printf "\n\n\nopenmaths-app successfully distilled to /dist\n\n"

			break;;
		No )
			printf "\n\n\nOk, maybe next time :-)\n\n"
			break;;
	esac
done