#!/bin/bash

sudo npm install bower@latest gulp@latest npm-check-updates@latest tsd@latest typescript@latest -g

sudo ncu -ua
sudo npm install

bower install

tsd install
tsd update --save --overwrite
tsd rebundle

gulp concatVendor compile-tsc compile-tsc-tests
